apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "tanuu-demo-env"
  description: "Templated demo env from default Tanuu Backstage"
  links:
    - url:  https://github.com/efidemos/infra
      title: GitHub Repo
      icon: github
spec:
  type: environment
  lifecycle: experimental
  owner: TechServices