apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test"
  description: "test"
  links:
    - url:  https://github.com/efidemos/infra
      title: GitHub Repo
      icon: github
spec:
  type: environment
  lifecycle: experimental
  owner: TechServices