apiVersion: tanuu.fi/v1alpha1
kind: Cluster
metadata:
  name: tanuu-demo-env
  namespace: default
  annotations:
    uptest.upbound.io/pre-delete-hook: testhooks/delete-release.sh
spec:
  id: tanuu-demo-env
  parameters:
    version: "1.26"
    nodes:
      count: 3
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
  writeConnectionSecretToRef:
    name: tanuu-demo-env-kubeconfig
    namespace: default
